<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="5" total="7" passed="2" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-06T15:14:04Z" name="sanity" finished-at="2024-10-06T15:14:35Z" duration-ms="31680">
    <groups>
      <group name="sanity">
        <method signature="LoginTest.TC01_LoginFailureTest()[pri:0, instance:testcases.LoginTest@4d02f94e]" name="TC01_LoginFailureTest" class="testcases.LoginTest"/>
        <method signature="LoginTest.TC02_LoginSuccessTest()[pri:0, instance:testcases.LoginTest@4d02f94e]" name="TC02_LoginSuccessTest" class="testcases.LoginTest"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2024-10-06T15:14:04Z" name="Test" finished-at="2024-10-06T15:14:35Z" duration-ms="31680">
      <class name="testcases.HomePageTest">
        <test-method is-config="true" signature="SetUpExcel()[pri:0, instance:testcases.HomePageTest@15aab8c6]" started-at="2024-10-06T15:14:04Z" name="SetUpExcel" finished-at="2024-10-06T15:14:04Z" duration-ms="21" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUpExcel -->
        <test-method is-config="true" signature="CloseExcel()[pri:0, instance:testcases.HomePageTest@15aab8c6]" started-at="2024-10-06T15:14:35Z" name="CloseExcel" finished-at="2024-10-06T15:14:35Z" duration-ms="21" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.apache.poi.xssf.usermodel.XSSFWorkbook.close()" because "this.wbook" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.xssf.usermodel.XSSFWorkbook.close()" because "this.wbook" is null
at testcases.BaseClass.CloseExcel(BaseClass.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.afterRun(TestRunner.java:725)
at org.testng.TestRunner.run(TestRunner.java:509)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseExcel -->
      </class> <!-- testcases.HomePageTest -->
      <class name="testcases.LoginTest">
        <test-method is-config="true" signature="SetUpDriver()[pri:0, instance:testcases.LoginTest@4d02f94e]" started-at="2024-10-06T15:14:04Z" name="SetUpDriver" finished-at="2024-10-06T15:14:13Z" duration-ms="9528" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUpDriver -->
        <test-method signature="TC01_LoginFailureTest()[pri:0, instance:testcases.LoginTest@4d02f94e]" started-at="2024-10-06T15:14:13Z" name="TC01_LoginFailureTest" description="Login success test" finished-at="2024-10-06T15:14:22Z" duration-ms="8606" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_LoginFailureTest -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:testcases.LoginTest@4d02f94e]" started-at="2024-10-06T15:14:22Z" name="TearDown" finished-at="2024-10-06T15:14:22Z" duration-ms="439" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="SetUpDriver()[pri:0, instance:testcases.LoginTest@4d02f94e]" started-at="2024-10-06T15:14:22Z" name="SetUpDriver" finished-at="2024-10-06T15:14:26Z" duration-ms="3501" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUpDriver -->
        <test-method signature="TC02_LoginSuccessTest()[pri:0, instance:testcases.LoginTest@4d02f94e]" started-at="2024-10-06T15:14:26Z" name="TC02_LoginSuccessTest" description="Login success test" finished-at="2024-10-06T15:14:35Z" duration-ms="9098" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_LoginSuccessTest -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:testcases.LoginTest@4d02f94e]" started-at="2024-10-06T15:14:35Z" name="TearDown" finished-at="2024-10-06T15:14:35Z" duration-ms="420" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- testcases.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- sanity -->
</testng-results>
